/*
 * registers.h
 *
 *  Created: 04/11/2022 22:46:18
 *  Author: Mohamed Khalil
 *  
 */ 


#ifndef REGISTERS_H_
#define REGISTERS_H_


#include "../Utilities/basetypes.h"


/************************************************************************/
/* Defines                                                              */
/************************************************************************/
#define REG_TWBR            (*((volatile uint8_t*) 0x20)) 
#define REG_TWSR            (*((volatile uint8_t*) 0x21)) 
#define REG_TWAR           	(*((volatile uint8_t*) 0x22)) 
#define REG_TWDR           	(*((volatile uint8_t*) 0x23)) 
#define REG_ADC           	(*((volatile uint16_t*) 0x24)) 
#define REG_ADCSRA          (*((volatile uint8_t*) 0x26)) 
#define REG_ADMUX           (*((volatile uint8_t*) 0x27)) 
#define REG_ACSR           	(*((volatile uint8_t*) 0x28)) 
#define REG_UBRRL           (*((volatile uint8_t*) 0x29)) 
#define REG_UCSRB           (*((volatile uint8_t*) 0x2A)) 
#define REG_UCSRA           (*((volatile uint8_t*) 0x2B)) 
#define REG_UDR           	(*((volatile uint8_t*) 0x2C)) 
#define REG_SPCR           	(*((volatile uint8_t*) 0x2D)) 
#define REG_SPSR          	(*((volatile uint8_t*) 0x2E)) 
#define REG_SPDR           	(*((volatile uint8_t*) 0x2F)) 
#define REG_PIND           	(*((volatile uint8_t*) 0x30)) 
#define REG_DDRD           	(*((volatile uint8_t*) 0x31)) 
#define REG_PORTD           (*((volatile uint8_t*) 0x32)) 
#define REG_PINC           	(*((volatile uint8_t*) 0x33)) 
#define REG_DDRC           	(*((volatile uint8_t*) 0x34)) 
#define REG_PORTC           (*((volatile uint8_t*) 0x35)) 
#define REG_PINB           	(*((volatile uint8_t*) 0x36)) 
#define REG_DDRB           	(*((volatile uint8_t*) 0x37)) 
#define REG_PORTB           (*((volatile uint8_t*) 0x38)) 
#define REG_PINA           	(*((volatile uint8_t*) 0x39)) 
#define REG_DDRA           	(*((volatile uint8_t*) 0x3A)) 
#define REG_PORTA           (*((volatile uint8_t*) 0x3B)) 
#define REG_EECR           	(*((volatile uint8_t*) 0x3C)) 
#define REG_EEDR           	(*((volatile uint8_t*) 0x3D)) 
#define REG_EEARL           (*((volatile uint8_t*) 0x3E)) 
#define REG_EEARH           (*((volatile uint8_t*) 0x3F)) 
#define REG_UCSRC           (*((volatile uint8_t*) 0x40)) 
#define REG_UBRRH           (*((volatile uint8_t*) 0x40)) 
#define REG_WDTCR           (*((volatile uint8_t*) 0x41)) 
#define REG_ASSR           	(*((volatile uint8_t*) 0x42)) 
#define REG_OCR2           	(*((volatile uint8_t*) 0x43)) 
#define REG_TCNT2           (*((volatile uint8_t*) 0x44)) 
#define REG_TCCR2          	(*((volatile uint8_t*) 0x45)) 
#define REG_ICR1L           (*((volatile uint8_t*) 0x46)) 
#define REG_ICR1H           (*((volatile uint8_t*) 0x47)) 
#define REG_OCR1B           (*((volatile uint16_t*) 0x48)) 
#define REG_OCR1A           (*((volatile uint16_t*) 0x4A)) 
#define REG_TCNT1           (*((volatile uint16_t*) 0x4C)) 
#define REG_TCCR1B          (*((volatile uint8_t*) 0x4E)) 
#define REG_TCCR1A          (*((volatile uint8_t*) 0x4F)) 
#define REG_SFIOR           (*((volatile uint8_t*) 0x50)) 
#define REG_OCDR           	(*((volatile uint8_t*) 0x51)) 
#define REG_OSCCAL          (*((volatile uint8_t*) 0x51)) 
#define REG_TCNT0           (*((volatile uint8_t*) 0x52)) 
#define REG_TCCR0           (*((volatile uint8_t*) 0x53)) 
#define REG_MCUCSR          (*((volatile uint8_t*) 0x54)) 
#define REG_MCUCR           (*((volatile uint8_t*) 0x55)) 
#define REG_TWCR           	(*((volatile uint8_t*) 0x56)) 
#define REG_SPMCR           (*((volatile uint8_t*) 0x57)) 
#define REG_TIFR           	(*((volatile uint8_t*) 0x58)) 
#define REG_TIMSK           (*((volatile uint8_t*) 0x59)) 
#define REG_GIFR           	(*((volatile uint8_t*) 0x5A)) 
#define REG_GICR           	(*((volatile uint8_t*) 0x5B)) 
#define REG_OCR0           	(*((volatile uint8_t*) 0x5C)) 
#define REG_SPL           	(*((volatile uint8_t*) 0x5D)) 
#define REG_SPH           	(*((volatile uint8_t*) 0x5E)) 
#define REG_SREG           	(*((volatile uint8_t*) 0x5F)) 

#define P_REG_TWBR            ((volatile uint8_t*) 0x20)
#define P_REG_TWSR            ((volatile uint8_t*) 0x21)
#define P_REG_TWAR           	((volatile uint8_t*) 0x22)
#define P_REG_TWDR           	((volatile uint8_t*) 0x23)
#define P_REG_ADC           	((volatile uint16_t*) 0x24)
#define P_REG_ADCSRA          ((volatile uint8_t*) 0x26)
#define P_REG_ADMUX           ((volatile uint8_t*) 0x27)
#define P_REG_ACSR           	((volatile uint8_t*) 0x28)
#define P_REG_UBRRL           ((volatile uint8_t*) 0x29)
#define P_REG_UCSRB           ((volatile uint8_t*) 0x2A)
#define P_REG_UCSRA           ((volatile uint8_t*) 0x2B)
#define P_REG_UDR           	((volatile uint8_t*) 0x2C)
#define P_REG_SPCR           	((volatile uint8_t*) 0x2D)
#define P_REG_SPSR          	((volatile uint8_t*) 0x2E)
#define P_REG_SPDR           	((volatile uint8_t*) 0x2F)
#define P_REG_PIND           	((volatile uint8_t*) 0x30)
#define P_REG_DDRD           	((volatile uint8_t*) 0x31)
#define P_REG_PORTD           ((volatile uint8_t*) 0x32)
#define P_REG_PINC           	((volatile uint8_t*) 0x33)
#define P_REG_DDRC           	((volatile uint8_t*) 0x34)
#define P_REG_PORTC           ((volatile uint8_t*) 0x35)
#define P_REG_PINB           	((volatile uint8_t*) 0x36)
#define P_REG_DDRB           	((volatile uint8_t*) 0x37)
#define P_REG_PORTB           ((volatile uint8_t*) 0x38)
#define P_REG_PINA           	((volatile uint8_t*) 0x39)
#define P_REG_DDRA           	((volatile uint8_t*) 0x3A)
#define P_REG_PORTA           ((volatile uint8_t*) 0x3B)
#define P_REG_EECR           	((volatile uint8_t*) 0x3C)
#define P_REG_EEDR           	((volatile uint8_t*) 0x3D)
#define P_REG_EEARL           ((volatile uint8_t*) 0x3E)
#define P_REG_EEARH           ((volatile uint8_t*) 0x3F)
#define P_REG_UCSRC           ((volatile uint8_t*) 0x40)
#define P_REG_UBRRH           ((volatile uint8_t*) 0x40)
#define P_REG_WDTCR           ((volatile uint8_t*) 0x41)
#define P_REG_ASSR           	((volatile uint8_t*) 0x42)
#define P_REG_OCR2           	((volatile uint8_t*) 0x43)
#define P_REG_TCNT2           ((volatile uint8_t*) 0x44)
#define P_REG_TCCR2          	((volatile uint8_t*) 0x45)
#define P_REG_ICR1L           ((volatile uint8_t*) 0x46)
#define P_REG_ICR1H           ((volatile uint8_t*) 0x47)
#define P_REG_OCR1B           ((volatile uint16_t*) 0x48)
#define P_REG_OCR1A           ((volatile uint16_t*) 0x4A)
#define P_REG_TCNT1           ((volatile uint16_t*) 0x4C)
#define P_REG_TCCR1B          ((volatile uint8_t*) 0x4E)
#define P_REG_TCCR1A          ((volatile uint8_t*) 0x4F)
#define P_REG_SFIOR           ((volatile uint8_t*) 0x50)
#define P_REG_OCDR           	((volatile uint8_t*) 0x51)
#define P_REG_OSCCAL          ((volatile uint8_t*) 0x51)
#define P_REG_TCNT0           ((volatile uint8_t*) 0x52)
#define P_REG_TCCR0           ((volatile uint8_t*) 0x53)
#define P_REG_MCUCSR          ((volatile uint8_t*) 0x54)
#define P_REG_MCUCR           ((volatile uint8_t*) 0x55)
#define P_REG_TWCR           	((volatile uint8_t*) 0x56)
#define P_REG_SPMCR           ((volatile uint8_t*) 0x57)
#define P_REG_TIFR           	((volatile uint8_t*) 0x58)
#define P_REG_TIMSK           ((volatile uint8_t*) 0x59)
#define P_REG_GIFR           	((volatile uint8_t*) 0x5A)
#define P_REG_GICR           	((volatile uint8_t*) 0x5B)
#define P_REG_OCR0           	((volatile uint8_t*) 0x5C)
#define P_REG_SPL           	((volatile uint8_t*) 0x5D)
#define P_REG_SPH           	((volatile uint8_t*) 0x5E)
#define P_REG_SREG            ((volatile uint8_t*) 0x5F)


#endif /* REGISTERS_H_ */